--CREATE DATABASE IF NOT EXISTS SOCIAL_NETWORK;
--USE SOCIAL_NETWORK;

CREATE TABLE IF NOT EXISTS USER(
        EMAIL VARCHAR(100) NOT NULL,
        NAME VARCHAR(100) NOT NULL,
        CITY VARCHAR(100) NOT NULL,
        PASSWORD VARCHAR(100) NOT NULL,
        PHONE VARCHAR(100) NOT NULL,
        BIRTHDAY DATE NOT NULL,
        PRIMARY KEY(EMAIL)
);

CREATE TABLE IF NOT EXISTS FOTOS(
    ID_DA_FOTO INT NOT NULL AUTO_INCREMENT,
    PROPRIETARIO_DA_FOTO VARCHAR(100) NOT NULL REFERENCES UTILIZADOR(NOME),
    DATA_DO_UPLOAD DATE,
    LINK_DA_FOTO VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID_DA_FOTO)
);

CREATE TABLE IF NOT EXISTS LIKES(
    ID_DO_LIKE INT NOT NULL AUTO_INCREMENT,
    ID_DO_UTILIZADOR VARCHAR(100) NOT NULL REFERENCES UTILIZADOR(EMAIL),
    ID_DA_FOTO VARCHAR(255) NOT NULL REFERENCES FOTOS(LINK_DA_FOTO),
    DATA_DO_LIKE DATE NOT NULL,
    PRIMARY KEY(ID_DO_LIKE)
);

CREATE TABLE IF NOT EXISTS DESLIKES(
    ID_DO_LIKE INT NOT NULL AUTO_INCREMENT,
    ID_DO_UTILIZADOR VARCHAR(100) NOT NULL REFERENCES UTILIZADOR(EMAIL),
    ID_DA_FOTO VARCHAR(255) NOT NULL REFERENCES FOTOS(LINK_DA_FOTO),
    DATA_DO_LIKE DATE NOT NULL,
    PRIMARY KEY(ID_DO_LIKE)
);


--truncate utilizador;
--truncate fotos;
--use looks_like
select * from user;